---
- hosts: leafs_DC2
  gather_facts: no
  tasks:
  - name: Register variables
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay.yml"
      name: config

  - name: Create Config Subdirectories if it does not exist
    ansible.builtin.file:
      path: ./configs/{{inventory_hostname}}
      state: directory

  - name: Configure Leaf Interfaces
    template:
      src: "{{lookup('env','PWD')}}/templates/leafs.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_underlay.cfg"
