---
- hosts: leafs_DC1
  gather_facts: no
  tasks:
  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/no_vlans.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}vlans.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}vlans.cfg"