# This playbook is to be used to generate spine MP-BGP config with variables from underlay.yml

---
- hosts: spines_DC2
  gather_facts: no
  tasks:
  - name: Register variables (candidates- Do not change this)
    include_vars:
      file: "{{lookup('env','PWD')}}/vars/underlay.yml"
      name: underlay

  - name: Create Config Subdirectories if it does not exist
    ansible.builtin.file:
      path: ./configs/{{inventory_hostname}}
      state: directory

  - name: Create template
    template:
      src: "{{lookup('env','PWD')}}/templates/spine.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_spine.cfg"
  # Use the eos_config module to create a task to upload the configuration you created to the switch

  - name: Upload Spine Underlay config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}/{{inventory_hostname}}_spine.cfg"
      
  - name: Save Switch Configuration
    eos_command:
      commands:
        - copy run start